#!/bin/bash
# <oldrev> <newrev> <refname>
# update a blame tree
DENY_FAST_FORWARD_FOR="refs/heads/master"

while read oldrev newrev ref
do
	if [[ "$oldrev" == "0000000000000000000000000000000000000000" ]]; then
		#create new branch
		continue;
	fi
	if [[ "${DENY_FAST_FORWARD_FOR}" =~ "${ref}" ]] ; then
		base=`git merge-base $oldrev $newrev`
		if [[ "${base}" != "${oldrev}" ]]; then
			#non fast-forward, mean force
			echo -e "\033[91mPlease don't force update to \"master\".\033[0m"
			exit 1
		fi
	fi
done

exit 0
