#!/usr/bin/env python
import sys
branch = sys.argv[1]
old_commit = sys.argv[2]
new_commit = sys.argv[3]
if branch !="refs/heads/master":
	sys.exit(0)
import requests
import json
import subprocess
if old_commit != "0000000000000000000000000000000000000000":
	proc = subprocess.Popen(['git','diff','--name-only',old_commit,new_commit],stdout=subprocess.PIPE)
else:
	proc = subprocess.Popen(['git','show','--pretty=',"--name-only",new_commit],stdout=subprocess.PIPE)
file_name="/main.c"
while True:
	line = proc.stdout.readline()
	if line != '':
		line=line[:-1]
		if(line.endswith(file_name)):
			front=line[:-len(file_name)]
			try:
				problem_id=int(front)
				if problem_id >=0:
					prc=subprocess.Popen(['git',"show",new_commit+':'+line],stdout=subprocess.PIPE, stderr=subprocess.PIPE)
					f=open("hooks/key")
					data={"file":prc.stdout.read(),"key":f.read()}
					f.close()
					if prc.wait() != 0:
						raise Exception('Not Found')
					#print json.dumps(data,ensure_ascii=False)
					print("\033[92mYou submit Problem #"+str(problem_id)+" !\033[0m")
					r = requests.post("https://ada18-judge.csie.org/submit/"+str(problem_id),json=data)
					try:
						result=json.loads(r.content)
						print("\033[93mSubmissin: \033[94mhttps://ada18-judge.csie.org/#!/submission/"+str(result["id"])+"\033[0m")
					except:
						print("\033[91m"+r.content+"\033[0m")
					#print "You submit Proble #"+str(problem_id)+" !"
			except:
				pass
		#print line
	else:
		break
#print "Moving '%s' from %s to %s" % (branch, old_commit, new_commit)
# Abort pushing only this branch
# sys.exit(1)
