swapoff -a
echo performance > /sys/devices/system/cpu/cpufreq/policy10/scaling_governor
echo performance > /sys/devices/system/cpu/cpufreq/policy11/scaling_governor
echo performance > /sys/devices/system/cpu/cpufreq/policy12/scaling_governor
echo performance > /sys/devices/system/cpu/cpufreq/policy13/scaling_governor
echo performance > /sys/devices/system/cpu/cpufreq/policy14/scaling_governor
echo performance > /sys/devices/system/cpu/cpufreq/policy15/scaling_governor
echo performance > /sys/devices/system/cpu/cpufreq/policy16/scaling_governor
echo performance > /sys/devices/system/cpu/cpufreq/policy17/scaling_governor
echo performance > /sys/devices/system/cpu/cpufreq/policy18/scaling_governor
echo performance > /sys/devices/system/cpu/cpufreq/policy19/scaling_governor
echo performance > /sys/devices/system/cpu/cpufreq/policy20/scaling_governor
echo performance > /sys/devices/system/cpu/cpufreq/policy21/scaling_governor
echo performance > /sys/devices/system/cpu/cpufreq/policy22/scaling_governor
echo performance > /sys/devices/system/cpu/cpufreq/policy23/scaling_governor
echo performance > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
echo performance > /sys/devices/system/cpu/cpufreq/policy1/scaling_governor
echo performance > /sys/devices/system/cpu/cpufreq/policy2/scaling_governor
echo performance > /sys/devices/system/cpu/cpufreq/policy3/scaling_governor
echo performance > /sys/devices/system/cpu/cpufreq/policy4/scaling_governor
echo performance > /sys/devices/system/cpu/cpufreq/policy5/scaling_governor
echo performance > /sys/devices/system/cpu/cpufreq/policy6/scaling_governor
echo performance > /sys/devices/system/cpu/cpufreq/policy7/scaling_governor
echo performance > /sys/devices/system/cpu/cpufreq/policy8/scaling_governor
echo performance > /sys/devices/system/cpu/cpufreq/policy9/scaling_governor
echo 0 > /proc/sys/kernel/randomize_va_space
echo never > /sys/kernel/mm/transparent_hugepage/enabled
echo never > /sys/kernel/mm/transparent_hugepage/defrag
echo 0 > /sys/kernel/mm/transparent_hugepage/khugepaged/defrag
./isolate/isolate-check-environment
